# Generated by Django 2.2.4 on 2019-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190811_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo2',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
    ]
