# Generated by Django 2.2.4 on 2019-08-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_titulo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='titulo2',
        ),
    ]
