# Generated by Django 2.2.4 on 2019-08-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190814_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_news_letter',
            field=models.TextField(default='Newsletter text'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_newsletter',
            field=models.CharField(default='title', max_length=25),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_last_posts',
            field=models.TextField(default='last posts'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_last_posts',
            field=models.CharField(default='Title', max_length=25),
        ),
    ]
