# Generated by Django 2.2.4 on 2019-09-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190815_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visit_num',
            field=models.IntegerField(default=0),
        ),
    ]
