# Generated by Django 2.2.4 on 2019-09-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_blog_visit_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='visit_num',
        ),
    ]
